import 'package:code_quiz_v2/models/language-model.dart';

final List<ProgrammingTutorial> programmingTutorial = [
  ProgrammingTutorial(
    id: 1,
    topic1Title: 'Hello World!',
    topic1Description:
        '''A "Hello, World!" is a simple program that outputs Hello, World! on the screen. Since it's a very simple program, it's often used to introduce a new programming language to a newbie.''',
    sample1Program: '''// Your First C++ Program

#include <iostream>

int main() {
    std::cout << "Hello World!";
    return 0;
}
''',
    sample1ProgramOutput: '''Hello World!''',
    program1Description: '''Working of C++ "Hello World!" Program
// Your First C++ Program

In C++, any line starting with // is a comment. Comments are intended for the person reading the code to better understand the functionality of the program. It is completely ignored by the C++ compiler.
#include <iostream>

The #include is a preprocessor directive used to include files in our program. The above code is including the contents of the iostream file.

This allows us to use cout in our program to print output on the screen.

For now, just remember that we need to use #include <iostream> to use cout that allows us to print output on the screen.
int main() {...}

A valid C++ program must have the main() function. The curly braces indicate the start and the end of the function.

The execution of code beings from this function.
std::cout << "Hello World!";

std::cout prints the content inside the quotation marks. It must be followed by << followed by the format string. In our example, "Hello World!" is the format string.

Note: ; is used to indicate the end of a statement.
return 0;

The return 0; statement is the "Exit status" of the program. In simple terms, the program ends with this statement.
''',
    topic2Title: 'Syntax',
    topic2Description: '',
    sample2Program: '',
    sample2ProgramOutput: '',
    program2Description: '',
    topic3Title: 'Data Types',
    topic3Description: '',
    sample3Program: '',
    sample3ProgramOutput: '',
    program3Description: '',
    topic4Title: 'Conditions',
    topic4Description: '',
    sample4Program: '',
    sample4ProgramOutput: '',
    program4Description: '',
    topic5Title: 'Loops',
    topic5Description: '',
    sample5Program: '',
    sample5ProgramOutput: '',
    program5Description: '',
    topic6Title: 'Function',
    topic6Description: '',
    sample6Program: '',
    sample6ProgramOutput: '',
    program6Description: '',
    topic7Title: 'Array',
    topic7Description: '',
    sample7Program: '',
    sample7ProgramOutput: '',
    program7Description: '',
    topic8Title: 'Pointer',
    topic8Description: '',
    sample8Program: '',
    sample8ProgramOutput: '',
    program8Description: '',
    topic9Title: 'String',
    topic9Description: '',
    sample9Program: '',
    sample9ProgramOutput: '',
    program9Description: '',
    topic10Title: 'Structure',
    topic10Description: '',
    sample10Program: '',
    sample10ProgramOutput: '',
    program10Description: '',
    topic11Title: 'OOP',
    topic11Description: '',
    sample11Program: '',
    sample11ProgramOutput: '',
    program11Description: '',
  ),
  ProgrammingTutorial(
    id: 2,
    topic1Title: 'Hello World!',
    topic1Description:
        '''A "Hello, World!" is a simple program that outputs Hello, World! on the screen. Since it's a very simple program, it's often used to introduce a new programming language to a newbie.''',
    sample1Program: '',
    sample1ProgramOutput: '',
    program1Description: '',
    topic2Title: 'Syntax',
    topic2Description: '',
    sample2Program: '',
    sample2ProgramOutput: '',
    program2Description: '',
    topic3Title: 'Data Types',
    topic3Description: '',
    sample3Program: '',
    sample3ProgramOutput: '',
    program3Description: '',
    topic4Title: 'Conditions',
    topic4Description: '',
    sample4Program: '',
    sample4ProgramOutput: '',
    program4Description: '',
    topic5Title: 'Loops',
    topic5Description: '',
    sample5Program: '',
    sample5ProgramOutput: '',
    program5Description: '',
    topic6Title: 'Function',
    topic6Description: '',
    sample6Program: '',
    sample6ProgramOutput: '',
    program6Description: '',
    topic7Title: 'Array',
    topic7Description: '',
    sample7Program: '',
    sample7ProgramOutput: '',
    program7Description: '',
    topic8Title: 'Pointer',
    topic8Description: '',
    sample8Program: '',
    sample8ProgramOutput: '',
    program8Description: '',
    topic9Title: 'String',
    topic9Description: '',
    sample9Program: '',
    sample9ProgramOutput: '',
    program9Description: '',
    topic10Title: 'Structure',
    topic10Description: '',
    sample10Program: '',
    sample10ProgramOutput: '',
    program10Description: '',
    topic11Title: 'OOP',
    topic11Description: '',
    sample11Program: '',
    sample11ProgramOutput: '',
    program11Description: '',
  ),
  ProgrammingTutorial(
    id: 3,
    topic1Title: 'Hello World!',
    topic1Description:
        '''A "Hello, World!" is a simple program that outputs Hello, World! on the screen. Since it's a very simple program, it's often used to introduce a new programming language to a newbie.''',
    sample1Program: '',
    sample1ProgramOutput: '',
    program1Description: '',
    topic2Title: 'Syntax',
    topic2Description: '',
    sample2Program: '',
    sample2ProgramOutput: '',
    program2Description: '',
    topic3Title: 'Data Types',
    topic3Description: '',
    sample3Program: '',
    sample3ProgramOutput: '',
    program3Description: '',
    topic4Title: 'Conditions',
    topic4Description: '',
    sample4Program: '',
    sample4ProgramOutput: '',
    program4Description: '',
    topic5Title: 'Loops',
    topic5Description: '',
    sample5Program: '',
    sample5ProgramOutput: '',
    program5Description: '',
    topic6Title: 'Function',
    topic6Description: '',
    sample6Program: '',
    sample6ProgramOutput: '',
    program6Description: '',
    topic7Title: 'Array',
    topic7Description: '',
    sample7Program: '',
    sample7ProgramOutput: '',
    program7Description: '',
    topic8Title: 'Pointer',
    topic8Description: '',
    sample8Program: '',
    sample8ProgramOutput: '',
    program8Description: '',
    topic9Title: 'String',
    topic9Description: '',
    sample9Program: '',
    sample9ProgramOutput: '',
    program9Description: '',
    topic10Title: 'Structure',
    topic10Description: '',
    sample10Program: '',
    sample10ProgramOutput: '',
    program10Description: '',
    topic11Title: 'OOP',
    topic11Description: '',
    sample11Program: '',
    sample11ProgramOutput: '',
    program11Description: '',
  ),
  ProgrammingTutorial(
    id: 4,
    topic1Title: 'Hello World!',
    topic1Description:
        '''A "Hello, World!" is a simple program that outputs Hello, World! on the screen. Since it's a very simple program, it's often used to introduce a new programming language to a newbie.''',
    sample1Program: '',
    sample1ProgramOutput: '',
    program1Description: '',
    topic2Title: 'Syntax',
    topic2Description: '',
    sample2Program: '',
    sample2ProgramOutput: '',
    program2Description: '',
    topic3Title: 'Data Types',
    topic3Description: '',
    sample3Program: '',
    sample3ProgramOutput: '',
    program3Description: '',
    topic4Title: 'Conditions',
    topic4Description: '',
    sample4Program: '',
    sample4ProgramOutput: '',
    program4Description: '',
    topic5Title: 'Loops',
    topic5Description: '',
    sample5Program: '',
    sample5ProgramOutput: '',
    program5Description: '',
    topic6Title: 'Function',
    topic6Description: '',
    sample6Program: '',
    sample6ProgramOutput: '',
    program6Description: '',
    topic7Title: 'Array',
    topic7Description: '',
    sample7Program: '',
    sample7ProgramOutput: '',
    program7Description: '',
    topic8Title: 'Pointer',
    topic8Description: '',
    sample8Program: '',
    sample8ProgramOutput: '',
    program8Description: '',
    topic9Title: 'String',
    topic9Description: '',
    sample9Program: '',
    sample9ProgramOutput: '',
    program9Description: '',
    topic10Title: 'Structure',
    topic10Description: '',
    sample10Program: '',
    sample10ProgramOutput: '',
    program10Description: '',
    topic11Title: 'OOP',
    topic11Description: '',
    sample11Program: '',
    sample11ProgramOutput: '',
    program11Description: '',
  ),
  ProgrammingTutorial(
    id: 5,
    topic1Title: 'Hello World!',
    topic1Description:
        '''A "Hello, World!" is a simple program that outputs Hello, World! on the screen. Since it's a very simple program, it's often used to introduce a new programming language to a newbie.''',
    sample1Program: '',
    sample1ProgramOutput: '',
    program1Description: '',
    topic2Title: 'Syntax',
    topic2Description: '',
    sample2Program: '',
    sample2ProgramOutput: '',
    program2Description: '',
    topic3Title: 'Data Types',
    topic3Description: '',
    sample3Program: '',
    sample3ProgramOutput: '',
    program3Description: '',
    topic4Title: 'Conditions',
    topic4Description: '',
    sample4Program: '',
    sample4ProgramOutput: '',
    program4Description: '',
    topic5Title: 'Loops',
    topic5Description: '',
    sample5Program: '',
    sample5ProgramOutput: '',
    program5Description: '',
    topic6Title: 'Function',
    topic6Description: '',
    sample6Program: '',
    sample6ProgramOutput: '',
    program6Description: '',
    topic7Title: 'Array',
    topic7Description: '',
    sample7Program: '',
    sample7ProgramOutput: '',
    program7Description: '',
    topic8Title: 'Pointer',
    topic8Description: '',
    sample8Program: '',
    sample8ProgramOutput: '',
    program8Description: '',
    topic9Title: 'String',
    topic9Description: '',
    sample9Program: '',
    sample9ProgramOutput: '',
    program9Description: '',
    topic10Title: 'Structure',
    topic10Description: '',
    sample10Program: '',
    sample10ProgramOutput: '',
    program10Description: '',
    topic11Title: 'OOP',
    topic11Description: '',
    sample11Program: '',
    sample11ProgramOutput: '',
    program11Description: '',
  ),
  ProgrammingTutorial(
    id: 6,
    topic1Title: 'Hello World!',
    topic1Description:
        '''A "Hello, World!" is a simple program that outputs Hello, World! on the screen. Since it's a very simple program, it's often used to introduce a new programming language to a newbie.''',
    sample1Program: '',
    sample1ProgramOutput: '',
    program1Description: '',
    topic2Title: 'Syntax',
    topic2Description: '',
    sample2Program: '',
    sample2ProgramOutput: '',
    program2Description: '',
    topic3Title: 'Data Types',
    topic3Description: '',
    sample3Program: '',
    sample3ProgramOutput: '',
    program3Description: '',
    topic4Title: 'Conditions',
    topic4Description: '',
    sample4Program: '',
    sample4ProgramOutput: '',
    program4Description: '',
    topic5Title: 'Loops',
    topic5Description: '',
    sample5Program: '',
    sample5ProgramOutput: '',
    program5Description: '',
    topic6Title: 'Function',
    topic6Description: '',
    sample6Program: '',
    sample6ProgramOutput: '',
    program6Description: '',
    topic7Title: 'Array',
    topic7Description: '',
    sample7Program: '',
    sample7ProgramOutput: '',
    program7Description: '',
    topic8Title: 'Pointer',
    topic8Description: '',
    sample8Program: '',
    sample8ProgramOutput: '',
    program8Description: '',
    topic9Title: 'String',
    topic9Description: '',
    sample9Program: '',
    sample9ProgramOutput: '',
    program9Description: '',
    topic10Title: 'Structure',
    topic10Description: '',
    sample10Program: '',
    sample10ProgramOutput: '',
    program10Description: '',
    topic11Title: 'OOP',
    topic11Description: '',
    sample11Program: '',
    sample11ProgramOutput: '',
    program11Description: '',
  ),
];
