import 'package:code_quiz_v2/models/language-model.dart';

final List<CategoryTopic> categoryTile = [
  CategoryTopic(
      id: 1,
      name: 'C/C++',
      imagePath: 'images/c_logo.png',
      topic1: 'Hello World',
      topic2: 'Syntax',
      topic3: 'Data Types',
      topic4: 'Conditions',
      topic5: 'Loops',
      topic6: 'Function',
      topic7: 'Array',
      topic8: 'Pointer',
      topic9: 'String',
      topic10: 'Structure',
      topic11: 'OOP'),
  CategoryTopic(
      id: 2,
      name: 'Java',
      imagePath: 'images/java_logo.png',
      topic1: 'Hello World',
      topic2: 'Syntax',
      topic3: 'Data Types',
      topic4: 'Conditions',
      topic5: 'Loops',
      topic6: 'Function',
      topic7: 'Array',
      topic8: 'Pointer',
      topic9: 'String',
      topic10: 'Structure',
      topic11: 'OOP'),
  CategoryTopic(
      id: 3,
      name: 'Python',
      imagePath: 'images/python_logo.png',
      topic1: 'Hello World',
      topic2: 'Syntax',
      topic3: 'Data Types',
      topic4: 'Conditions',
      topic5: 'Loops',
      topic6: 'Function',
      topic7: 'Array',
      topic8: 'Pointer',
      topic9: 'String',
      topic10: 'Structure',
      topic11: 'OOP'),
  CategoryTopic(
      id: 4,
      name: 'Dart',
      imagePath: 'images/dart_logo.png',
      topic1: 'Hello World',
      topic2: 'Syntax',
      topic3: 'Data Types',
      topic4: 'Conditions',
      topic5: 'Loops',
      topic6: 'Function',
      topic7: 'Array',
      topic8: 'Pointer',
      topic9: 'String',
      topic10: 'Structure',
      topic11: 'OOP'),
  CategoryTopic(
      id: 5,
      name: 'Swift',
      imagePath: 'images/swift_logo.png',
      topic1: 'Hello World',
      topic2: 'Syntax',
      topic3: 'Data Types',
      topic4: 'Conditions',
      topic5: 'Loops',
      topic6: 'Function',
      topic7: 'Array',
      topic8: 'Pointer',
      topic9: 'String',
      topic10: 'Structure',
      topic11: 'OOP'),
  CategoryTopic(
      id: 6,
      name: 'JavaScript',
      imagePath: 'images/js_logo.png',
      topic1: 'Hello World',
      topic2: 'Syntax',
      topic3: 'Data Types',
      topic4: 'Conditions',
      topic5: 'Loops',
      topic6: 'Function',
      topic7: 'Array',
      topic8: 'Pointer',
      topic9: 'String',
      topic10: 'Structure',
      topic11: 'OOP'),
];
