import 'package:code_quiz_v2/models/language-model.dart';

final List<ProgrammingTutorial> programmingTutorial = [
  ProgrammingTutorial(
    id: 1,
    topic1Title: 'Hello World',
    topic1Description: '',
    sample1Program: '',
    program1Description: '',
    topic2Title: 'Syntax',
    topic2Description: '',
    sample2Program: '',
    program2Description: '',
    topic3Title: 'Data Types',
    topic3Description: '',
    sample3Program: '',
    program3Description: '',
    topic4Title: 'Conditions',
    topic4Description: '',
    sample4Program: '',
    program4Description: '',
    topic5Title: 'Loops',
    topic5Description: '',
    sample5Program: '',
    program5Description: '',
    topic6Title: 'Function',
    topic6Description: '',
    sample6Program: '',
    program6Description: '',
    topic7Title: 'Array',
    topic7Description: '',
    sample7Program: '',
    program7Description: '',
    topic8Title: 'Pointer',
    topic8Description: '',
    sample8Program: '',
    program8Description: '',
    topic9Title: 'String',
    topic9Description: '',
    sample9Program: '',
    program9Description: '',
    topic10Title: 'Structure',
    topic10Description: '',
    sample10Program: '',
    program10Description: '',
  ),
  ProgrammingTutorial(
    id: 2,
    topic1Title: 'Hello World',
    topic1Description: '',
    sample1Program: '',
    program1Description: '',
    topic2Title: 'Syntax',
    topic2Description: '',
    sample2Program: '',
    program2Description: '',
    topic3Title: 'Data Types',
    topic3Description: '',
    sample3Program: '',
    program3Description: '',
    topic4Title: 'Conditions',
    topic4Description: '',
    sample4Program: '',
    program4Description: '',
    topic5Title: 'Loops',
    topic5Description: '',
    sample5Program: '',
    program5Description: '',
    topic6Title: 'Function',
    topic6Description: '',
    sample6Program: '',
    program6Description: '',
    topic7Title: 'Array',
    topic7Description: '',
    sample7Program: '',
    program7Description: '',
    topic8Title: 'Pointer',
    topic8Description: '',
    sample8Program: '',
    program8Description: '',
    topic9Title: 'String',
    topic9Description: '',
    sample9Program: '',
    program9Description: '',
    topic10Title: 'Structure',
    topic10Description: '',
    sample10Program: '',
    program10Description: '',
  ),
  ProgrammingTutorial(
    id: 3,
    topic1Title: 'Hello World',
    topic1Description: '',
    sample1Program: '',
    program1Description: '',
    topic2Title: 'Syntax',
    topic2Description: '',
    sample2Program: '',
    program2Description: '',
    topic3Title: 'Data Types',
    topic3Description: '',
    sample3Program: '',
    program3Description: '',
    topic4Title: 'Conditions',
    topic4Description: '',
    sample4Program: '',
    program4Description: '',
    topic5Title: 'Loops',
    topic5Description: '',
    sample5Program: '',
    program5Description: '',
    topic6Title: 'Function',
    topic6Description: '',
    sample6Program: '',
    program6Description: '',
    topic7Title: 'Array',
    topic7Description: '',
    sample7Program: '',
    program7Description: '',
    topic8Title: 'Pointer',
    topic8Description: '',
    sample8Program: '',
    program8Description: '',
    topic9Title: 'String',
    topic9Description: '',
    sample9Program: '',
    program9Description: '',
    topic10Title: 'Structure',
    topic10Description: '',
    sample10Program: '',
    program10Description: '',
  ),
  ProgrammingTutorial(
    id: 4,
    topic1Title: 'Hello World',
    topic1Description: '',
    sample1Program: '',
    program1Description: '',
    topic2Title: 'Syntax',
    topic2Description: '',
    sample2Program: '',
    program2Description: '',
    topic3Title: 'Data Types',
    topic3Description: '',
    sample3Program: '',
    program3Description: '',
    topic4Title: 'Conditions',
    topic4Description: '',
    sample4Program: '',
    program4Description: '',
    topic5Title: 'Loops',
    topic5Description: '',
    sample5Program: '',
    program5Description: '',
    topic6Title: 'Function',
    topic6Description: '',
    sample6Program: '',
    program6Description: '',
    topic7Title: 'Array',
    topic7Description: '',
    sample7Program: '',
    program7Description: '',
    topic8Title: 'Pointer',
    topic8Description: '',
    sample8Program: '',
    program8Description: '',
    topic9Title: 'String',
    topic9Description: '',
    sample9Program: '',
    program9Description: '',
    topic10Title: 'Structure',
    topic10Description: '',
    sample10Program: '',
    program10Description: '',
  ),
  ProgrammingTutorial(
    id: 5,
    topic1Title: 'Hello World',
    topic1Description: '',
    sample1Program: '',
    program1Description: '',
    topic2Title: 'Syntax',
    topic2Description: '',
    sample2Program: '',
    program2Description: '',
    topic3Title: 'Data Types',
    topic3Description: '',
    sample3Program: '',
    program3Description: '',
    topic4Title: 'Conditions',
    topic4Description: '',
    sample4Program: '',
    program4Description: '',
    topic5Title: 'Loops',
    topic5Description: '',
    sample5Program: '',
    program5Description: '',
    topic6Title: 'Function',
    topic6Description: '',
    sample6Program: '',
    program6Description: '',
    topic7Title: 'Array',
    topic7Description: '',
    sample7Program: '',
    program7Description: '',
    topic8Title: 'Pointer',
    topic8Description: '',
    sample8Program: '',
    program8Description: '',
    topic9Title: 'String',
    topic9Description: '',
    sample9Program: '',
    program9Description: '',
    topic10Title: 'Structure',
    topic10Description: '',
    sample10Program: '',
    program10Description: '',
  ),
  ProgrammingTutorial(
    id: 6,
    topic1Title: 'Hello World',
    topic1Description: '',
    sample1Program: '',
    program1Description: '',
    topic2Title: 'Syntax',
    topic2Description: '',
    sample2Program: '',
    program2Description: '',
    topic3Title: 'Data Types',
    topic3Description: '',
    sample3Program: '',
    program3Description: '',
    topic4Title: 'Conditions',
    topic4Description: '',
    sample4Program: '',
    program4Description: '',
    topic5Title: 'Loops',
    topic5Description: '',
    sample5Program: '',
    program5Description: '',
    topic6Title: 'Function',
    topic6Description: '',
    sample6Program: '',
    program6Description: '',
    topic7Title: 'Array',
    topic7Description: '',
    sample7Program: '',
    program7Description: '',
    topic8Title: 'Pointer',
    topic8Description: '',
    sample8Program: '',
    program8Description: '',
    topic9Title: 'String',
    topic9Description: '',
    sample9Program: '',
    program9Description: '',
    topic10Title: 'Structure',
    topic10Description: '',
    sample10Program: '',
    program10Description: '',
  ),
];
