import 'package:code_quiz_v2/models/language-model.dart';

final List<CategoryTopic> categoryTile = [
  CategoryTopic(
    id: 1,
    name: 'C/C++',
    imagePath: 'images/c_logo.png',
    topic1: 'Hello World',
    topic2: 'Syntax',
    topic3: 'Data Types',
    topic4: 'Conditions',
    topic5: 'Loops',
    topic6: 'Function',
    topic7: 'Pointer',
    topic8: 'Class',
    topic9: 'Object',
    topic10: 'Inheritence',
  ),
  CategoryTopic(
    id: 2,
    name: 'Java',
    imagePath: 'images/java_logo.png',
    topic1: 'Hello World',
    topic2: 'Syntax',
    topic3: 'Data Types',
    topic4: 'Conditions',
    topic5: 'Loops',
    topic6: 'Function',
    topic7: 'Pointer',
    topic8: 'Class',
    topic9: 'Object',
    topic10: 'Inheritence',
  ),
  CategoryTopic(
    id: 3,
    name: 'Python',
    imagePath: 'images/python_logo.png',
    topic1: 'Hello World',
    topic2: 'Syntax',
    topic3: 'Data Types',
    topic4: 'Conditions',
    topic5: 'Loops',
    topic6: 'Function',
    topic7: 'Pointer',
    topic8: 'Class',
    topic9: 'Object',
    topic10: 'Inheritence',
  ),
  CategoryTopic(
    id: 4,
    name: 'Dart',
    imagePath: 'images/dart_logo.png',
    topic1: 'Hello World',
    topic2: 'Syntax',
    topic3: 'Data Types',
    topic4: 'Conditions',
    topic5: 'Loops',
    topic6: 'Function',
    topic7: 'Pointer',
    topic8: 'Class',
    topic9: 'Object',
    topic10: 'Inheritence',
  ),
  CategoryTopic(
    id: 5,
    name: 'HTML/CSS',
    imagePath: 'images/html_logo.png',
    topic1: 'Tags',
    topic2: 'Body',
    topic3: 'Heading',
    topic4: 'Paragraph',
    topic5: 'Div',
    topic6: '',
    topic7: '',
    topic8: '',
    topic9: '',
    topic10: '',
  ),
  CategoryTopic(
    id: 6,
    name: 'JavaScript',
    imagePath: 'images/js_logo.png',
    topic1: 'Hello World',
    topic2: 'Syntax',
    topic3: 'Data Types',
    topic4: 'Conditions',
    topic5: 'Loops',
    topic6: 'Function',
    topic7: 'Pointer',
    topic8: 'Class',
    topic9: 'Object',
    topic10: 'Inheritence',
  ),
];
